#' @name get.edge.stats
#' 
#' @description a function that takes as input an edge frequencies data frame 
#'              (as generated by the get.edge.freq() function) and calculates 
#'              some statistics for each edge. Namely, calculates a mean weighted 
#'              distance and a weight (meanDist and weight columns respectively).
#' 
#' @param edge.frq The data frame of edge frequencies as generated by the 
#'                 get.edge.freq() function.
#' 
#' @export


get.edge.stats <- function(edge.frq){
    
    
    edge.frq <- edge.frq %>%
        mutate(meanDist = wDistSum/count) %>%
        mutate(weight = 1/(meanDist/obsFreq))
    
    return(edge.frq)
    
}
